### ISSUE TITLE
GUI builder generates non valid CSS for font format

### ISSUE THREAD

**Issue by gaeoh** [lunafromthemoon/RenJS-V2#10]
The GUI builder generates CSS like this:
`
      @font-face {

          font-family: 'fontsaudimat-mono';

          src: url('/assets/gui/fontsfontsaudimat-mono.ttf');

          src: url('/assets/gui/fontsfontsaudimat-mono.ttf').format('truetype');

         // ...

      }
`
With `.format` instead of ` format` with a spece between.

**Comment by gaeoh** [comment]
Also, are both src:-lines necessary?

**Comment by lunafromthemoon** [comment]
Thanks for reporting, I will add this issue to the GUI Builder repository.
