### ISSUE TITLE
Add versions numbers and a changelog

### ISSUE THREAD

**Issue by gaeoh** [lunafromthemoon/RenJS-V2#18]
Recently a GUI update changed some stuff. I think it would be nice to have version numbers, and a (simple) changelog. Maybe we also also need to tag releases to make #6 possible?

**Comment by gaeoh** [comment]
Ok,so I _think_ this is the only current reference to a version number? https://github.com/lunafromthemoon/RenJS-V2/commit/7ae2c0b45cd93e8494e5e1ef2dfa087d475fac8f

**Comment by lunafromthemoon** [comment]
I tried to do that but I don't think I got quite there. Do you have any suggestion where to keep track of this? 
I also added now a version for the GUI, since that's important for parsing the new format.

**Comment by gaeoh** [comment]
Just dumping a link for a nice changelog format here: https://keepachangelog.com/en/1.0.0/

**Comment by gaeoh** [comment]
And maybe also this for version numbering? https://semver.org/
