### ISSUE TITLE
Words jumping to next line due to text-wrapping

### ISSUE THREAD

**Issue by seleb** [lunafromthemoon/RenJS-V2#30]
Text wrapping seems to be getting re-calculated as individual characters print to the screen, which makes words jump from the end of a line to the beginning of the next line when they hit the edge. This is a bit clunky: it'd be a smoother read if all of the wrapping was handled up-front, and characters appeared already in their final positions one-by-one.

**Comment by lunafromthemoon** [comment]
This is fixed by the configuration property 'precomputeBreakLines' in config.yaml
It's off by default for compatibility reasons.
