### ISSUE TITLE
Docs: couple typos/confusing language

### ISSUE THREAD

**Issue by seleb** [lunafromthemoon/RenJS-V2#36]
Couple minor typos spotted in docs:

 - `asignation` -> `assignation`
 - `rigth` -> `right`

Note that "assignation" is also a bit strange terminology-wise: afaik "assignment" is usually the term used in this context (I've heard "assignation" far more often as the alternate definition of "meeting to have an affair" haha).

**Comment by lunafromthemoon** [comment]
Thanks, I'm not that good at english. Fixed now.
